version: '2'
services:
  mongo:
    image: mongo:3.4.4
    volumes:
     - ./data:/data
    command: --smallfiles
  nodeapi:
    build: ./app
    volumes:
     - ./config:/usr/src/app/config
    ports:
     - "3200:3000"
